



void beep(void);
void burp(void);
void savecursor(void);
void retcursor(void);
void hidecursor(void);
void showcursor(void);
void clearall(void);
void textlinev(int col, int start, int finish, int topch, int botch);
void textlineh(int row, int start, int finish);
int startcell(enum coltype col);
int endcell(enum coltype col);
void showcell(celltype cell);
void showall(void);
void entercell(celltype cell);
void leavecell(celltype cell);
void drawborder(void);
void setuparray(void);
void reinstall(void);
void outnum(int x, int y,char *num, int colourt);
void mapnum(void);
void drawheadings(void);
void drawcommands(void);
void drawstatus(void);
void errormessage(char  *message);
void goleft(void);
void goright(void);
void goup(void);
void godown(void);
void movement(void);
void filedelete(void);
double getpricezoom(void);
int inputinteger(int x,int y,int defnum,int max);
long inputlinteger(int x,int y,long defnum,int max);
int printdetails(void);
double inputreal(int x,int y,double defnum,int max,int dec);
void showsysdate(void);
int inputdate(int x, int y, char  *date);
int inputstring( int x, int y, char  *string);
void writefile(char  *fname);
void loadfile(char *fname);
int inputmonth(int x, int y, int month);
double ndf(double x);
void bs();
void blankrow(int row);
void blankall(void);
void blankcell(celltype cell);
void showrow(int row);
void calcrow(int row);
void convertdate(char *date,int *year,int *month,int *day);
void makewindow(int x1,int y1,int x2,int y2,char  *header);
void closewindow(int x1,int y1,int x2,int y2);
double divprice(int future);
void newfile(void);
int findmonth(char *month);
void filldates(void);
void fillpay(void);
void inithelp(void);
int choice(int n,char *ch[]);
void CBS(double volpct,double strike,double stock,
        double rpct,int days,double  *valuec,double  *deltac);
void PBS(double volpct,double strike,double stock,
        double rpct,int days,double  *valuep,double  *deltap);
int driveready(void);
int drawgraph(int typeofgraph);
int shmultiplier(int month);
int serialdate( int year, int month, int day);
int recallsys(void);
void savesys(void);
void ready(void);
void disppage(void);
int dtx(int month);
int mindtx(void);
int maxdtx(void);
int printdetails(void);
int printdetailt(void);
int printdetailu(void);
void wait(void);
int graphmode(void);
void calcvalgraph(void);
void startgraph(void);
void calctimegraph(int numdays,double interval);
void calcvalgraph1(void);
void calctimegraph1(int numdays,double interval);
void anykey(void);
void waitkey(void);
void initialise(void);
void systemdate(void);
void initdates(void);
void calcdays(void);
void initsizepay(void);
void calcall(void);
void genscreen(void);
void help(void);
void sortstatus(void);
void clearrow(void);
void getdir(void);
void bonusissue(void);
int gettimechoice(void);
void CBSdiv(double volpct,double strike,double stock,
        double rpct,int days,double  *valuec,double  *deltac);
void PBSdiv(double volpct,double strike,double stock,
        double rpct,int days,double  *valuep,double  *deltap);

void initdivmtx(int future);
void totals(void);
void showtotals(void);
double getintervalchoice(void);
int pirated(void);

void calcvolrow(int row);
void calcallvol(void);
double invertvolc(int row);
double invertvolp(int row);
void cashissue(void);
long inputlint(int x,int y,long *defnum,int max);
int optpr(void);
void rowleft(void);
void rowright(void);
void tabright(void);
void calcoverval(int row);
void graphyval(void);
void graphxval(void);
void starttext(void);
void graphvaluesout(void);
void tableft(void);
void calcalloverval(void);
int choosefunction(void);
void demo(void);
void showhelp(char  *heading,char  *text);
void encode(char *name,char *coded);
void copyright(void);