/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "nfs.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

void *
nfsproc3_null_3(void *argp, CLIENT *clnt)
{
	static char clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, NFSPROC3_NULL,
		(xdrproc_t) xdr_void, (caddr_t) argp,
		(xdrproc_t) xdr_void, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return ((void *)&clnt_res);
}

LOOKUP3res *
nfsproc3_lookup_3(LOOKUP3args *argp, CLIENT *clnt)
{
	static LOOKUP3res clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, NFSPROC3_LOOKUP,
		(xdrproc_t) xdr_LOOKUP3args, (caddr_t) argp,
		(xdrproc_t) xdr_LOOKUP3res, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

WRITE3res *
nfsproc3_write_3(WRITE3args *argp, CLIENT *clnt)
{
	static WRITE3res clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, NFSPROC3_WRITE,
		(xdrproc_t) xdr_WRITE3args, (caddr_t) argp,
		(xdrproc_t) xdr_WRITE3res, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

COMMIT3res *
nfsproc3_commit_3(COMMIT3args *argp, CLIENT *clnt)
{
	static COMMIT3res clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, NFSPROC3_COMMIT,
		(xdrproc_t) xdr_COMMIT3args, (caddr_t) argp,
		(xdrproc_t) xdr_COMMIT3res, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
