#!/bin/bash

cd $HOME/tsums || exit 1
PATHS="/dev /sbin /lib /etc /bin /usr/bin /usr/sbin /usr/lib"
NOTIFY="tridge@samba.org tridge@valinux.com"

export PATH=/bin:/sbin:/usr/bin:$PATH

nice ./tsums -f tsums.tdb $PATHS > tsums.out 2>&1

if [ -s tsums.out ]; then
   Mail -s 'URGENT tsums' $NOTIFY < tsums.out
fi
